// import { Geist, Geist_Mono } from "next/font/google";
import {  Inter, Elza } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: "--font-inter",
  subsets: ["latin"],
});
// const elza = Elza({
//   variable: "--font-elza",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${inter.variable} antialiased`}

      >
        {children}
      </body>
    </html>
  );
}
